export interface ListItem {
  name: string;
  address: string;
  description: string;
  detail?: string;
  personalNote?: string;
  meta?: Record<string, string>;
}

export interface TableColumn {
  key: string;
  label: string;
  emoji: string;
}

export interface ListData {
  slug: string;
  title: string;
  subtitle: string;
  emoji: string;
  color: string;
  image: string;
  story: string;
  closingNote: string;
  tableColumns: TableColumn[];
  items: ListItem[];
}

export const allLists: ListData[] = [
  // {
  //   slug: "studentkafeer",
  //   title: "Studentvennlige Kafeer",
  //   subtitle: "",//"For de dagene det ikke frister å sitte hjemme eller på lesesalen.",
  //   emoji: "☕",
  //   color: "#C4B5A0",
  //   image: "https://images.unsplash.com/photo-1558210834-473f430c09ac?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",//"https://images.unsplash.com/photo-1753613648131-f8189bf05bcf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3p5JTIwY2FmZSUyMHN0dWR5aW5nJTIwbGFwdG9wJTIwY29mZmVlfGVufDF8fHx8MTc3MjgzMzA3Mnww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
  //   story: "For de dagene det ikke frister å sitte hjemme eller på lesesalen.",//"Som studenter og trofaste kaffeelskere har vi notert oss noen favoritter for de dagene det ikke frister like mye å sitte hjemme eller på lesesalen. For at de skal nå opp på vår liste, kreves det en eller flere av følgende: trådløst nett, studentrabatt, godt mat og drikke, samt lademuligheter. Tekst & foto: Lene Myrum Haugen og Mari F. Karlsen.",
  //   closingNote: "PS! Ta med studentbevis — det lønner seg! Sentralen, Cafe Sør, Kulturhuset og Fuglen gir alle studentrabatt.",
  //   tableColumns: [
  //     { key: "area", label: "Område", emoji: "📍" },
  //     { key: "wifi", label: "WiFi", emoji: "📶" },
  //     { key: "outlets", label: "Stikkontakter", emoji: "🔌" },
  //     { key: "studentDeal", label: "Studentrabatt", emoji: "🎓" },
  //     { key: "bestFor", label: "Best for", emoji: "✨" },
  //   ],
  //   items: [
  //     { name: "Grød", address: "Markveien 67, Oslo", description: "Danske vibes på Grünerløkka med mer enn bare grøt — til studentvennlige priser. Store og små bord som passer like godt for deg som vil jobbe alene som for studiegruppen.", detail: "Grøt fra 95–159 kr, pluss bowls, sideretter og vafler", personalNote: "Stikkontakter under benkene — de har tenkt på alt. Perfekt for en lang økt med god frokost først.", meta: { area: "Grünerløkka", wifi: "Gratis", outlets: "Under benkene", studentDeal: "Studentvennlige priser", bestFor: "Studiegrupper" } },
  //     { name: "Nasjonalbibliotekbaren (Credo)", address: "Henrik Ibsens gate 110, Oslo", description: "En lys og luftig kafé i andre etasje på Nasjonalbiblioteket med god kaffe, fersk bakst og en rolig atmosfære som passer perfekt for studier eller gruppearbeid.", detail: "Lesesal og bibliotek rett ved siden av", personalNote: "Begrenset med stikkontakter — kom oppladet og godt forberedt. Men atmosfæren er blant de mest inspirerende i byen.", meta: { area: "Sentrum", wifi: "Gratis", outlets: "Begrenset", studentDeal: "Nei", bestFor: "Konsentrert arbeid" } },
  //     { name: "Tranen (Åpent Bakeri)", address: "Waldemar Thranes gate 70, Oslo", description: "Midt på Alexander Kiellands plass, der mange av Oslos busslinjer møtes. Rikelig med sitteplasser og en meny som dekker de fleste cravings.", detail: "Frokost, lett lunsj, kaffe og bakst", personalNote: "Kan bli fullt i ukedagene — ta gjerne med headset. På fine dager kan du slå deg ned ute og nyte sola. Bare husk å lade opp PC-en først!", meta: { area: "Kiellands plass", wifi: "Gratis", outlets: "Noen få", studentDeal: "Nei", bestFor: "Møtested for grupper" } },
  //     { name: "Café Laundromat", address: "Underhaugsveien 2, Oslo", description: "Kanskje Oslos mest unike kafé — her kan du nemlig både spise, drikke og vaske klær samtidig. Perfekt hvis vaskemaskinen i kollektivet har streika.", detail: "Brunsj- og lunsjmeny + vaskemaskiner", personalNote: "Retro-vibe som minner om en amerikansk milkshakebar. Mange kommer hit i grupper og blir sittende hele dagen.", meta: { area: "Bislett", wifi: "Gratis", outlets: "Ja", studentDeal: "Nei", bestFor: "Lange skriveøkter" } },
  //     { name: "Sentralen Kafé", address: "Øvre Slottsgate 3, Oslo", description: "Hipp vibe med radene av folk ved vinduene med laptopen foran seg. Omgivelser uten for mye støy, med kaffelukten tydelig i luften.", detail: "Større bord og grupperom kan bookes", personalNote: "15% studentrabatt! Et tilbud vi mener er gull verdt for både korte kaffepauser og lange studiedager.", meta: { area: "Sentrum", wifi: "Gratis", outlets: "Ja", studentDeal: "15% rabatt", bestFor: "Alene eller i grupper" } },
  //     { name: "Papegøye", address: "Urtegata 48, Oslo", description: "Et fargerikt lite pusterom på Grønland som kan gi deg et ekstra energikick når innleveringen føles seig. Om kvelden forvandles kafeen til en vin- og cocktailbar.", detail: "God kaffe, myke boller og store cookies", personalNote: "Funker både for morgenfugler og nattugler — kafé på dagen, cocktailbar på kvelden.", meta: { area: "Grønland", wifi: "Gratis", outlets: "Ja", studentDeal: "Nei", bestFor: "Kreativt arbeid" } },
  //     { name: "Pust Kaffebar", address: "Slemdalsveien 1, Oslo", description: "En relativt kjent og hipp kafé på Majorstua med industri-inspirert interiør, sofagrupper og vanlige bord. Folk kommer hit for å jobbe, strikke, skravle eller bare nyte kaffe.", detail: "Smørbrød, bakevarer, kaffe, te — og gløgg i førjulstiden!", personalNote: "Stedet føles veldig koselig og inkluderende. De har også Frokostklubben — perfekt for å bli bedre kjent med studiegruppen.", meta: { area: "Majorstua", wifi: "Gratis", outlets: "Ja", studentDeal: "Nei", bestFor: "Hygge og arbeid" } },
  //     { name: "Cafe Sør", address: "Torggata 11, Oslo", description: "Mest forbundet med cocktails og nattklubb, men også en ypperlig plass for studietimer på dagtid. Mørkt lokale med murvegger, retro interiør og lounge-/jazzmusikk.", detail: "25% studentrabatt på mat + gratis svart kaffe", personalNote: "Gratis svart kaffe for studenter! Og pasjonsfruktisten deres er helt fantastisk. Vi vender stadig tilbake hit.", meta: { area: "Sentrum", wifi: "Bra", outlets: "Ved de fleste bord", studentDeal: "25% + gratis kaffe", bestFor: "Lange studiedager" } },
  //     { name: "Kulturhuset", address: "Youngs gate 6, Oslo", description: "Stort sted ved Youngstorget med flere etasjer, kafé og bar. Nett og masse stikkontakter. Kafé med kjøkken som serverer lunsjretter på dagtid.", detail: "25% på kaffe, 10% på mineralvann, hver 6. kaffe gratis", personalNote: "Perfekt for å studere sammen med flere. Kom tidlig for store bord! Om det er fullt, prøv Youngs i samme bygg.", meta: { area: "Youngstorget", wifi: "Gratis", outlets: "Masse", studentDeal: "25% kaffe + kaffekort", bestFor: "Store grupper" } },
  //     { name: "Fuglen", address: "Universitetsgata 2 / St. Halvards gate 33, Oslo", description: "Godt kjent kafé- og cocktailbar med originalt interiør fra 60-tallet. Kaffe av høyeste kvalitet i hyggelige omgivelser — finnes i både Oslo og Tokyo!", detail: "10% på svart kaffe for studenter (Universitetsgata)", personalNote: "De fleste kaffe-nerder i Oslo har tittet innom her. Genuin sjarm — mye av interiøret kan faktisk kjøpes!", meta: { area: "Sentrum / Gamlebyen", wifi: "Gratis", outlets: "Noen", studentDeal: "10% svart kaffe", bestFor: "Kaffeelskere" } },
  //     { name: "Skatten", address: "Hagegata 22-24, Oslo", description: "Kafé om dagen og bar om kvelden på Tøyen torg. Store vinduer med utsikt over Tøyen, mange store bord, koselige sofaer og kroker perfekt for studiedagene.", detail: "Chai latte anbefales — fyldig og god", personalNote: "Absolutt en skatt — med hjemmekoselig interiør. Om det er fullt her, finnes det flere kafeer på Tøyen torg!", meta: { area: "Tøyen", wifi: "Gratis", outlets: "Ja", studentDeal: "Nei", bestFor: "Studiegrupper og soloarbeid" } },
  //   ],
  // },
  // {
  //   slug: "billig-pils",
  //   title: "Billigst Pils i Oslo",
  //   subtitle: "",//"55 steder med halvliter under 100 kroner. Oppdatert for 2024.",
  //   emoji: "🍺",
  //   color: "#F0D48B",
  //   image: "https://plus.unsplash.com/premium_photo-1695285406073-0424d330c075?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  //   story: "55 steder med halvliter under 100 kroner. Oppdatert for 2024.",//"88 kroner halvliteren i Molde — sa VG Nett om Festivalsommeren. Men hva med Oslo? Prisene er fra 2024, og 0,4 er omregnet til pris per halvliter. Sporadisk ajourføring: 2025 — Heim i Ullevålsveien har nå 0,6 til kr 99 på torsdag–lørdag.",
  //   closingNote: "Prisene endrer seg stadig. Sjekk gjerne før du går — og nyt sola mens den varer.",
  //   tableColumns: [
  //     { key: "price", label: "Pris (halvliter)", emoji: "💰" },
  //     { key: "area", label: "Område", emoji: "📍" },
  //     { key: "condition", label: "Betingelse", emoji: "⏰" },
  //   ],
  //   items: [
  //     { name: "Rett inn bar", address: "Storgata, Oslo", description: "Oslos billigste halvliter — rett og slett.", personalNote: "60 kroner. Det er nesten svensk pris.", meta: { price: "kr 60", area: "Sentrum", condition: "Alltid" } },
  //     { name: "Mastermind", address: "Schweigaardsgate, Oslo", description: "Like billig som Rett inn, gjemt bort i Schweigaardsgate.", meta: { price: "kr 60", area: "Sentrum øst", condition: "Alltid" } },
  //     { name: "Heidis bar", address: "Tordenskjoldsgate, Oslo", description: "Rimelig øl helt til kl 23. Sentralt beliggende.", meta: { price: "kr 61", area: "Sentrum", condition: "Til kl 23" } },
  //     { name: "Alf", address: "Kiellands plass, Oslo", description: "Billig pils fram til kl 19 — perfekt etter jobb.", meta: { price: "kr 64", area: "Kiellands plass", condition: "Til kl 19" } },
  //     { name: "Wright", address: "Sørengas østside, Oslo", description: "Sjøutsikt og 69-kronerspils. Vanskelig å slå.", personalNote: "En av de bedre uteserveringene i byen.", meta: { price: "kr 69", area: "Sørenga", condition: "Alltid" } },
  //     { name: "Under Brua Bar", address: "Grønlandsleiret, Oslo", description: "Rett under brua — et lokalt stamsted.", meta: { price: "kr 69", area: "Grønland", condition: "Alltid" } },
  //     { name: "Enerhaugen pub", address: "Grønland (v/politihuset), Oslo", description: "Klassisk nabolagspub ved Grønland.", meta: { price: "kr 69", area: "Grønland", condition: "Alltid" } },
  //     { name: "Los Tacos (Sørenga)", address: "Sørenga indre del, Oslo", description: "Tacos og billig øl med utsikt til Bjørvika.", meta: { price: "kr 69", area: "Sørenga", condition: "Til kl 21" } },
  //     { name: "Café Cortado", address: "Sandaker (Nordpolen), Oslo", description: "Rolig nabolagskafé på Nordpolen.", meta: { price: "kr 69", area: "Sandaker", condition: "Alltid" } },
  //     { name: "Valentino", address: "Ovenfor Carl Berner, Oslo", description: "Lokalt tilholdssted ovenfor Carl Berner.", meta: { price: "kr 69", area: "Carl Berner", condition: "Alltid" } },
  //     { name: "Sandaker café", address: "Vogtsgate, Oslo", description: "Stamkafé i Vogtsgate med lave priser.", meta: { price: "kr 70", area: "Sandaker", condition: "Alltid" } },
  //     { name: "Los Tacos (Torggata)", address: "Torggata, Oslo", description: "Ettermiddagspils til 69 kroner i Torggata.", meta: { price: "kr 69", area: "Sentrum", condition: "Ettermiddag" } },
  //     { name: "Bydelskroa", address: "Jens Bjelkes gate (Tøyen), Oslo", description: "Ekte bydelskro på Tøyen.", meta: { price: "kr 74", area: "Tøyen", condition: "Alltid" } },
  //     { name: "London pub", address: "Rosenkrantzgate (v/Hambros plass), Oslo", description: "Britisk pub-stemning midt i sentrum.", meta: { price: "kr 78", area: "Sentrum", condition: "Alltid" } },
  //     { name: "Bobs pub", address: "Grønlandsleiret, Oslo", description: "Enkelt og greit — billig øl på Grønland.", meta: { price: "kr 79", area: "Grønland", condition: "Alltid" } },
  //     { name: "Gamle Renna", address: "v/Sinsenkrysset, Oslo", description: "Veteranen ved Sinsenkrysset.", meta: { price: "kr 79", area: "Sinsen", condition: "Alltid" } },
  //     { name: "Sagene bar", address: "Bentsegata, Oslo", description: "Nabolagsbar med sjel på Sagene.", meta: { price: "kr 79", area: "Sagene", condition: "Alltid" } },
  //     { name: "Sorrento", address: "Grønlandsleiret, Oslo", description: "Enda et godt alternativ i Grønlandsleiret.", meta: { price: "kr 79", area: "Grønland", condition: "Alltid" } },
  //     { name: "Sverres café", address: "Carl Berner, Oslo", description: "Klassisk kafé ved Carl Berner.", meta: { price: "kr 83", area: "Carl Berner", condition: "Alltid" } },
  //     { name: "Waffl", address: "Schweigaards gate, Oslo", description: "Vafler og billig pils — en god kombinasjon.", meta: { price: "kr 83", area: "Sentrum øst", condition: "Alltid" } },
  //     { name: "Hersleb grill og bar", address: "Trondhjemsveien, Oslo", description: "Grill og bar langs Trondhjemsveien.", meta: { price: "kr 85", area: "Tøyen", condition: "Alltid" } },
  //     { name: "Uvisst", address: "Tordenskjoldsgate (v/Rådhuset), Oslo", description: "Rimelig øl til kl 23, nær Rådhuset.", meta: { price: "kr 86", area: "Sentrum", condition: "Til kl 23" } },
  //     { name: "Cacadou", address: "Torggata, Oslo", description: "En institusjon i Torggata.", meta: { price: "kr 88", area: "Sentrum", condition: "Alltid" } },
  //     { name: "Ocean", address: "Trondhjemsveien, Oslo", description: "Asiatisk restaurant med billig øl.", meta: { price: "kr 89", area: "Tøyen", condition: "Alltid" } },
  //     { name: "Orlandos", address: "Fredensborg (Rostedsgate), Oslo", description: "Nabolagspub på Fredensborg.", meta: { price: "kr 89", area: "Fredensborg", condition: "Alltid" } },
  //     { name: "Rudolf", address: "Vestli t-banestasjon, Oslo", description: "Helt ute på Vestli — men prisen er riktig.", meta: { price: "kr 89", area: "Vestli", condition: "Alltid" } },
  //     { name: "Beef Buns", address: "Middelthunsgate (Majorstua), Oslo", description: "Burgere og billig øl etter kl 17.", meta: { price: "kr 90", area: "Majorstua", condition: "Etter kl 17" } },
  //     { name: "Café Stambul", address: "Vogtsgate (Torshov), Oslo", description: "Koselig kafé på Torshov.", meta: { price: "kr 92", area: "Torshov", condition: "Alltid" } },
  //     { name: "Mad Goat Tap Room", address: "Grønland (Teaterplassen), Oslo", description: "Craft beer-bar med overraskende lave priser.", meta: { price: "kr 92", area: "Grønland", condition: "Alltid" } },
  //     { name: "Perrongen", address: "Majorstua, Oslo", description: "Rett ved Majorstua stasjon.", meta: { price: "kr 92", area: "Majorstua", condition: "Alltid" } },
  //     { name: "Naboens", address: "Grünerløkka, Oslo", description: "Nabolagspub midt på Løkka.", meta: { price: "kr 93", area: "Grünerløkka", condition: "Alltid" } },
  //     { name: "Valkyrien", address: "Majorstua, Oslo", description: "Populært utested på Majorstua.", meta: { price: "kr 93", area: "Majorstua", condition: "Alltid" } },
  //     { name: "Bellas bistro", address: "Grefsenveien, Oslo", description: "Hyggelig bistro på Grefsen.", meta: { price: "kr 94", area: "Grefsen", condition: "Alltid" } },
  //     { name: "Enga", address: "Vålerenga, Oslo", description: "Vålerenga-pub med lokalt preg.", meta: { price: "kr 94", area: "Vålerenga", condition: "Alltid" } },
  //     { name: "St.Bar", address: "St.Hanshaugen, Oslo", description: "Populær bar på St.Hanshaugen.", meta: { price: "kr 94", area: "St.Hanshaugen", condition: "Alltid" } },
  //     { name: "Szechuan", address: "Trondhjemsveien, Oslo", description: "Kinesisk restaurant med billig halvliter.", meta: { price: "kr 94", area: "Tøyen", condition: "Alltid" } },
  //     { name: "Marienlyst café", address: "Kirkeveien (Blindern), Oslo", description: "Studentvennlig kafé nær Blindern.", meta: { price: "kr 94", area: "Blindern", condition: "Alltid" } },
  //     { name: "Paviljongen", address: "Bjerkedalen park, Oslo", description: "Flott beliggenhet i Bjerkedalen park.", personalNote: "Perfekt for en sommerøl i parken.", meta: { price: "kr 95", area: "Bjerkedalen", condition: "Alltid" } },
  //     { name: "Din Deli", address: "Kristian Augusts gate, Oslo", description: "Deli med rimelig øl i sentrum.", meta: { price: "kr 96", area: "Sentrum", condition: "Alltid" } },
  //     { name: "Peloton", address: "Torggata, Oslo", description: "Sykkel-bar i Torggata.", meta: { price: "kr 96", area: "Sentrum", condition: "Alltid" } },
  //     { name: "Radegast vinbar", address: "Akerselva/Nedre Foss, Oslo", description: "Vinbar ved Akerselva med billig pils.", meta: { price: "kr 96", area: "Grünerløkka", condition: "Alltid" } },
  //     { name: "Hagestuen", address: "v/Tøyen torg, Oslo", description: "Sjarmerende sted ved Tøyen torg.", meta: { price: "kr 96", area: "Tøyen", condition: "Alltid" } },
  //     { name: "Asylet", address: "Grønlandsleiret, Oslo", description: "Kultursted og bar på Grønland.", meta: { price: "kr 98", area: "Grønland", condition: "Alltid" } },
  //     { name: "Brewgata", address: "Brugata, Oslo", description: "Øl-fokusert bar i Brugata.", meta: { price: "kr 98", area: "Sentrum øst", condition: "Alltid" } },
  //     { name: "Kontoret", address: "Oslogate, Oslo", description: "Gammeldags pub i Oslogate.", meta: { price: "kr 98", area: "Gamlebyen", condition: "Alltid" } },
  //     { name: "Ladegården", address: "Oslogate, Oslo", description: "Historisk beliggenhet i Oslogate.", meta: { price: "kr 98", area: "Gamlebyen", condition: "Alltid" } },
  //     { name: "Kraft", address: "Kværnerbyen, Oslo", description: "Nytt tilskudd i Kværnerbyen.", meta: { price: "kr 98", area: "Kværnerbyen", condition: "Alltid" } },
  //     { name: "Tekehtopa", address: "St.Olavs plass, Oslo", description: "Apoteket baklengs — studentbar ved St.Olavs plass.", meta: { price: "kr 98", area: "Sentrum", condition: "Alltid" } },
  //     { name: "The Pub", address: "Majorstuegata, Oslo", description: "Britisk pub-stil på Majorstua.", meta: { price: "kr 98", area: "Majorstua", condition: "Alltid" } },
  //     { name: "Trattoria Populare", address: "Schous plass, Oslo", description: "Italiensk trattoria med billig pils.", meta: { price: "kr 98", area: "Grünerløkka", condition: "Alltid" } },
  //     { name: "Tyren", address: "Vogtsgate, Oslo", description: "Pub i Vogtsgate.", meta: { price: "kr 98", area: "Torshov", condition: "Alltid" } },
  //     { name: "Vålerenga vertshus", address: "Strømsveien, Oslo", description: "Tradisjonelt vertshus på Vålerenga.", meta: { price: "kr 98", area: "Vålerenga", condition: "Alltid" } },
  //     { name: "Bella Notte", address: "Carl Berner, Oslo", description: "Italiensk stemning ved Carl Berner.", meta: { price: "kr 99", area: "Carl Berner", condition: "Alltid" } },
  //     { name: "Apsorn Thai", address: "Torshov (Soria Moria), Oslo", description: "Thaimat og billig øl på Torshov.", meta: { price: "kr 99", area: "Torshov", condition: "Alltid" } },
  //     { name: "Bar G18", address: "Grønlandsleiret, Oslo", description: "Bar i Grønlandsleiret 18.", meta: { price: "kr 99", area: "Grønland", condition: "Alltid" } },
  //     { name: "Café Sara", address: "Torggata, Oslo", description: "Populær kafé i Torggata.", meta: { price: "kr 99", area: "Sentrum", condition: "Alltid" } },
  //     { name: "Peoples", address: "Torggata v/Sentrum scene, Oslo", description: "Rett ved Sentrum scene.", meta: { price: "kr 99", area: "Sentrum", condition: "Alltid" } },
  //     { name: "Café Teater", address: "Torshovgata, Oslo", description: "Teater-kafé på Torshov.", meta: { price: "kr 99", area: "Torshov", condition: "Alltid" } },
  //     { name: "Kampen pub", address: "Hedmarksgata, Oslo", description: "Kampen-klassiker i Hedmarksgata.", meta: { price: "kr 99", area: "Kampen", condition: "Alltid" } },
  //     { name: "NAB Kitchen Bar", address: "Majorstua (v/Colosseum), Oslo", description: "Moderne kjøkken-bar ved Colosseum.", meta: { price: "kr 99", area: "Majorstua", condition: "Alltid" } },
  //     { name: "Nam Kang", address: "Fredensborgveien, Oslo", description: "Asiatisk mat og rimelig øl.", meta: { price: "kr 99", area: "Fredensborg", condition: "Alltid" } },
  //     { name: "Sofies mat- og vinhus", address: "Nedenfor Parkveien, Oslo", description: "Mat- og vinhus med overraskende billig pils.", meta: { price: "kr 99", area: "Sentrum vest", condition: "Alltid" } },
  //     { name: "Trafalgar", address: "Akersgata (v/Hambros plass), Oslo", description: "Pub i Akersgata — god beliggenhet.", meta: { price: "kr 99", area: "Sentrum", condition: "Alltid" } },
  //     { name: "Vesuvio", address: "Theresegata (Bislett), Oslo", description: "Italiensk restaurant ved Bislett med billig pils.", meta: { price: "kr 99", area: "Bislett", condition: "Alltid" } },
  //   ],
  // },
  {
    slug: "Restaurant",
    title: "Byens beste pizza",
    subtitle: "",//"Places I keep going back to, no matter what.",
    emoji: "🍽️",
    color: "#E8D5C4",
    image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    story: "Kommer snart ...",//"I once ate at 4 restaurants in a single day trying to settle an argument with a friend about which had the best pasta. Nobody won — my stomach lost. These are the survivors of years of enthusiastic (and occasionally reckless) dining.",
    closingNote: "",//"If you only try one, make it The Golden Fork. And if you disagree, I'd love to argue about it over dinner.",
    tableColumns: [
      // { key: "price", label: "Price", emoji: "💰" },
      // { key: "bestFor", label: "Best for", emoji: "✨" },
      // { key: "bestTime", label: "Best time", emoji: "🕐" },
      // { key: "reservation", label: "Reservation", emoji: "📞" },
      // { key: "rating", label: "My rating", emoji: "⭐" },
    ],
    items: [
      // { name: "The Golden Fork", address: "12 Rue des Jardins, 75004", description: "Farm-to-table perfection with seasonal menus that never disappoint.", detail: "Order the mushroom risotto", personalNote: "I've been here 23 times. I counted.", meta: { price: "€€€", bestFor: "Date night", bestTime: "Fri–Sat evening", reservation: "Essential", rating: "10/10" } },
      // { name: "Noma's Corner", address: "87 Strandgade, 1401", description: "Nordic-inspired small plates in an intimate candlelit setting.", detail: "Try the fermented plum dessert", personalNote: "Where I go when I need to feel fancy.", meta: { price: "€€€€", bestFor: "Special occasion", bestTime: "Weekday dinner", reservation: "2 weeks ahead", rating: "9.5/10" } },
      // { name: "Casa del Mare", address: "3 Promenade du Port, 06230", description: "Coastal Italian with the freshest catch and handmade pasta.", detail: "The lobster linguine is unreal", personalNote: "My go-to for impressing dates.", meta: { price: "€€€", bestFor: "Seafood lovers", bestTime: "Sunday lunch", reservation: "Recommended", rating: "9/10" } },
      // { name: "Saffron & Smoke", address: "41 Brick Lane, E1 6PU", description: "Modern Middle Eastern with bold flavors and beautiful presentation.", detail: "Don't skip the lamb shoulder", personalNote: "I dream about the hummus.", meta: { price: "€€", bestFor: "Group dinner", bestTime: "Thu–Sat", reservation: "Walk-in OK", rating: "9/10" } },
      // { name: "The Vine", address: "28 Calle de la Libertad, 28004", description: "Natural wine bar with a short but brilliant menu.", detail: "Ask the sommelier to surprise you", personalNote: "I've never ordered from the menu here. Trust them.", meta: { price: "€€–€€€", bestFor: "Wine lovers", bestTime: "Late evening", reservation: "Not needed", rating: "9/10" } },
      // { name: "Chez Maman", address: "55 Rue du Faubourg Saint-Denis, 75010", description: "Classic French bistro that feels like a warm hug.", detail: "The duck confit is a must", personalNote: "Reminds me of my grandmother's kitchen.", meta: { price: "€€", bestFor: "Comfort food", bestTime: "Weekday lunch", reservation: "Walk-in OK", rating: "8.5/10" } },
      // { name: "Ember & Ash", address: "9 Warehouse Row, SE1 3PA", description: "Open-fire cooking with locally sourced meats and vegetables.", detail: "The charred leeks are incredible", personalNote: "Everything tastes like a campfire in the best way.", meta: { price: "€€€", bestFor: "Meat lovers", bestTime: "Weekend dinner", reservation: "Recommended", rating: "9/10" } },
      // { name: "Jade Garden", address: "108 Canton Road, Tsim Sha Tsui", description: "No-frills Cantonese with the best dim sum in town.", detail: "Go early on weekends", personalNote: "Arrive at 10am or accept your fate in the queue.", meta: { price: "€", bestFor: "Dim sum brunch", bestTime: "Sat–Sun 10am", reservation: "No reservations", rating: "9.5/10" } },
      // { name: "Pueblo", address: "22 Calle de Echegaray, 28014", description: "Mexican street food elevated to an art form.", detail: "The mole negro took 3 days to make", personalNote: "The margaritas are dangerously good.", meta: { price: "€€", bestFor: "Casual night out", bestTime: "Fri evening", reservation: "Walk-in only", rating: "8.5/10" } },
      // { name: "Terroir", address: "5 Place du Marché Sainte-Catherine, 75004", description: "Tasting menus that change weekly, always a surprise.", detail: "Worth every penny", personalNote: "Save this for a special occasion.", meta: { price: "€€€€", bestFor: "Anniversary", bestTime: "Saturday", reservation: "1 month ahead", rating: "10/10" } },
    ],
  },
  {
    slug: "Kaffe",
    title: "Kaféer i Seoul",
    subtitle: " ",//"Tested extensively with my laptop and a flat white.",
    emoji: "☕",
    color: "#D4C5A9",
    image: "https://images.unsplash.com/photo-1622517806875-92161d3fd09d?q=80&w=1335&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    story: "Kommer snart ...",//"My criteria: WiFi speed above 50mbps, at least two power outlets per table, not too loud, not too quiet, and — this is non-negotiable — good coffee. I've been kicked out of exactly one café for staying too long. It didn't make the list.",
    closingNote: " ",//"Pro tip: always buy a second drink if you've been there more than 2 hours. Be a good café citizen.",
    tableColumns: [
      // { key: "wifi", label: "WiFi", emoji: "📶" },
      // { key: "outlets", label: "Outlets", emoji: "🔌" },
      // { key: "noise", label: "Noise level", emoji: "🔊" },
      // { key: "coffee", label: "Coffee", emoji: "☕" },
      // { key: "bestTime", label: "Best time", emoji: "🕐" },
    ],
    items: [
      // { name: "Slow Press", address: "14 Bermondsey Street, SE1 3TQ", description: "Big communal tables, great espresso, zero pretension.", detail: "Power outlets everywhere", personalNote: "I wrote most of my portfolio here.", meta: { wifi: "Fast (80mbps)", outlets: "Plenty", noise: "Low hum", coffee: "★★★★★", bestTime: "Early morning" } },
      // { name: "The Reading Room", address: "7 Rue Charlot, 75003", description: "Quiet enough to think, lively enough to not feel lonely.", detail: "The chai latte is perfect", personalNote: "My Thursday ritual spot.", meta: { wifi: "Good (60mbps)", outlets: "Some", noise: "Quiet", coffee: "★★★★☆", bestTime: "Afternoon" } },
      // { name: "Bloom Coffee", address: "32 Great Eastern Street, EC2A 3ES", description: "Light-filled corner spot with plants and V60 pour-overs.", detail: "Try the cardamom cold brew", personalNote: "The barista remembers my order. I feel seen.", meta: { wifi: "Good (55mbps)", outlets: "Limited", noise: "Gentle", coffee: "★★★★★", bestTime: "Mid-morning" } },
      // { name: "Workshop", address: "80 Mortimer Street, W1W 7FE", description: "Industrial vibes, fast WiFi, and the best cinnamon bun.", detail: "Gets busy after 10am", personalNote: "The cinnamon bun alone is worth the trip.", meta: { wifi: "Fastest (100mbps)", outlets: "Every table", noise: "Moderate", coffee: "★★★★☆", bestTime: "Before 10am" } },
      // { name: "Café Analog", address: "15 Vestergade, 1456", description: "Vinyl records playing, no rush, excellent batch brew.", detail: "Cash only on weekends", personalNote: "Time moves differently in here.", meta: { wifi: "OK (40mbps)", outlets: "Few", noise: "Music plays", coffee: "★★★★☆", bestTime: "Anytime" } },
      // { name: "Folio", address: "44 Lamb's Conduit Street, WC1N 3LJ", description: "Bookshop-café hybrid with a rotating library.", detail: "The matcha is ceremonial grade", personalNote: "Dangerous for my book-buying habit.", meta: { wifi: "Good (50mbps)", outlets: "Some", noise: "Whisper quiet", coffee: "★★★★★", bestTime: "Rainy days" } },
      // { name: "Groundwork", address: "26 De Beauvoir Crescent, N1 5SU", description: "Roasts their own beans on-site. You can smell it from the street.", detail: "Single origin espresso only", personalNote: "My coffee snobbery started here. Sorry.", meta: { wifi: "Good (65mbps)", outlets: "Plenty", noise: "Moderate", coffee: "★★★★★", bestTime: "Late morning" } },
      // { name: "The Perch", address: "Rooftop, 1 Angel Court, EC2R 7HJ", description: "Rooftop café with city views and surprisingly good pastries.", detail: "Best sunset spot in town", personalNote: "Where I go to pretend I'm in a movie.", meta: { wifi: "OK (35mbps)", outlets: "Limited", noise: "Breezy", coffee: "★★★☆☆", bestTime: "Golden hour" } },
      // { name: "Nook", address: "53 Redchurch Street, E2 7DJ", description: "Tiny, cozy, and somehow always has a seat for you.", detail: "Their sourdough toast is elite", personalNote: "Feels like working from a friend's living room.", meta: { wifi: "Good (55mbps)", outlets: "Some", noise: "Cozy murmur", coffee: "★★★★☆", bestTime: "Weekday AM" } },
      // { name: "Common Ground", address: "19 Hackney Road, E2 7NX", description: "Community-run, pay-what-you-can, exceptional quality.", detail: "Donate generously", personalNote: "Proof that good things can exist in this world.", meta: { wifi: "Good (50mbps)", outlets: "Plenty", noise: "Lively", coffee: "★★★★☆", bestTime: "Weekday PM" } },
    ],
  },
  // {
  //   slug: "swimming",
  //   title: "Best Swimming Spots Nearby",
  //   subtitle: "For when the city gets too hot and you need water.",
  //   emoji: "🏊",
  //   color: "#B8D4E3",
  //   image: "https://images.unsplash.com/photo-1619688136947-64abcd9ef940?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuYXR1cmFsJTIwc3dpbW1pbmclMjBsYWtlJTIwc3VtbWVyfGVufDF8fHx8MTc3MjgzMDQ1NXww&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
  //   story: "I didn't grow up near the ocean, so every swim still feels like a small miracle. I've been systematically visiting every swimmable body of water within a 2-hour drive. Some were transcendent. One gave me a rash. This list only includes the transcendent ones.",
  //   closingNote: "Always swim with a buddy. And bring a towel — I learned that the hard way at Crystal Lake in October.",
  //   tableColumns: [
  //     { key: "type", label: "Type", emoji: "💧" },
  //     { key: "season", label: "Best season", emoji: "📅" },
  //     { key: "drive", label: "Drive time", emoji: "🚗" },
  //     { key: "crowd", label: "Crowd level", emoji: "👥" },
  //     { key: "facilities", label: "Facilities", emoji: "🚿" },
  //   ],
  //   items: [
  //     { name: "Crystal Lake", address: "Chemin du Lac, Forêt de Montmorency, 95160", description: "Clear water, sandy bottom, surrounded by pine trees.", detail: "Best at sunrise", personalNote: "I once had this entire lake to myself at 6am. Peak life.", meta: { type: "Freshwater lake", season: "Jun–Sep", drive: "45 min", crowd: "Low", facilities: "None" } },
  //     { name: "The Old Quarry", address: "Quarry Lane, Blue Mountains, NSW 2780", description: "Deep turquoise water in a dramatic stone amphitheater.", detail: "Bring water shoes", personalNote: "Looks like a movie set. Feels even better.", meta: { type: "Quarry pool", season: "Jul–Aug", drive: "1 hr", crowd: "Medium", facilities: "Parking only" } },
  //     { name: "Willow Creek Bend", address: "Off Route 7, near Willow Bridge, VT 05753", description: "A lazy river bend with a natural sandy beach.", detail: "Perfect for kids too", personalNote: "Where I go to do absolutely nothing.", meta: { type: "River", season: "May–Sep", drive: "30 min", crowd: "Low–Med", facilities: "Picnic tables" } },
  //     { name: "Tidal Pool at Sunset Rocks", address: "Coastal Path, Sunset Rocks, Cape Town 8005", description: "Natural rock pools refreshed by the ocean twice daily.", detail: "Check tide times first", personalNote: "Found a starfish here once. We bonded.", meta: { type: "Tidal pool", season: "Year-round", drive: "50 min", crowd: "Low", facilities: "None" } },
  //     { name: "The Reservoir", address: "Reservoir Road, Staines-upon-Thames, TW18 2QF", description: "Calm, vast, with a 2km swimming loop for the ambitious.", detail: "Wetsuits recommended Oct–Apr", personalNote: "My longest swim: 45 minutes. My ego: enormous.", meta: { type: "Reservoir", season: "Year-round", drive: "40 min", crowd: "Medium", facilities: "Changing rooms" } },
  //     { name: "Hidden Falls Pool", address: "Trailhead at Cascade Rd, Lorne VIC 3232", description: "A waterfall-fed plunge pool at the end of a short hike.", detail: "20-minute walk from parking", personalNote: "The cold will make you gasp. Then you'll feel alive.", meta: { type: "Plunge pool", season: "Jun–Aug", drive: "1.5 hr", crowd: "Very low", facilities: "None" } },
  //     { name: "Pier 7 Beach", address: "Pier 7, Embarcadero North, San Francisco 94111", description: "Urban beach with lifeguards and a surprisingly clean waterfront.", detail: "Food trucks nearby on weekends", personalNote: "For when you want to swim but also want tacos.", meta: { type: "Beach", season: "Jun–Sep", drive: "15 min", crowd: "High", facilities: "Full (showers, food)" } },
  //     { name: "Echo Cove", address: "Echo Cove Track, Abel Tasman, 7183", description: "Sheltered bay with calm water and underwater rock formations.", detail: "Great for snorkeling", personalNote: "I saw an octopus here. We made eye contact.", meta: { type: "Sheltered bay", season: "May–Oct", drive: "1 hr 15 min", crowd: "Low", facilities: "Parking only" } },
  //   ],
  // },
  // {
  //   slug: "bookshops",
  //   title: "Favorite Independent Bookshops",
  //   subtitle: "Where I lose track of time and money.",
  //   emoji: "📚",
  //   color: "#E3D5E8",
  //   image: "https://images.unsplash.com/photo-1771674069196-bc239b1410f9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpbmRlcGVuZGVudCUyMGJvb2tzaG9wJTIwc2hlbHZlcyUyMGNvenl8ZW58MXx8fHwxNzcyODMwNDU1fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
  //   story: "My apartment is 60% books by volume. I have a strict \"one in, one out\" policy that I have never once followed. These shops are responsible for most of my financial decisions (bad ones) and my happiest afternoons.",
  //   closingNote: "If a bookseller recommends something, always say yes. They have a sixth sense.",
  //   tableColumns: [
  //     { key: "specialty", label: "Specialty", emoji: "📖" },
  //     { key: "vibes", label: "Vibes", emoji: "✨" },
  //     { key: "hours", label: "Hours", emoji: "🕐" },
  //     { key: "hasCafe", label: "Café?", emoji: "☕" },
  //   ],
  //   items: [
  //     { name: "The Wandering Page", address: "18 Cecil Court, WC2N 4HE", description: "Curated fiction selection with handwritten staff picks on every shelf.", detail: "Check the basement for rare finds", personalNote: "I trust their recommendations more than any algorithm.", meta: { specialty: "Literary fiction", vibes: "Warm & woody", hours: "10am–8pm", hasCafe: "No" } },
  //     { name: "Ink & Paper", address: "42 Rivington Street, EC2A 3BN", description: "Specializes in art books, zines, and independent publishers.", detail: "They host readings on Thursdays", personalNote: "Where I discovered my favorite living author.", meta: { specialty: "Art & zines", vibes: "Gallery-like", hours: "11am–7pm", hasCafe: "No" } },
  //     { name: "Lighthouse Books", address: "43–45 West Nicolson Street, EH8 9DB", description: "Radical political bookshop with an incredible events calendar.", detail: "Great for non-fiction", personalNote: "This shop has changed the way I think. Literally.", meta: { specialty: "Politics & theory", vibes: "Activist energy", hours: "10am–6pm", hasCafe: "No" } },
  //     { name: "Chapter One", address: "5 Rue de l'Odéon, 75006", description: "Children's bookshop that adults secretly love even more.", detail: "Beautiful illustrated editions", personalNote: "I buy \"gifts for my niece\" that mysteriously end up on my shelf.", meta: { specialty: "Children's & illustrated", vibes: "Colorful & joyful", hours: "9am–6pm", hasCafe: "No" } },
  //     { name: "The Map Room", address: "8 Holland Street, W8 4LT", description: "Travel writing, atlases, and adventure literature.", detail: "Vintage maps on the walls", personalNote: "Every visit makes me want to quit my job and sail somewhere.", meta: { specialty: "Travel & adventure", vibes: "Explorer's den", hours: "10am–7pm", hasCafe: "No" } },
  //     { name: "Volumes", address: "205 Stoke Newington High Street, N16 0LH", description: "General bookshop with a café and a cat named Hemingway.", detail: "Hemingway approves of your choices", personalNote: "Hemingway once sat on my laptop. I considered it a blessing.", meta: { specialty: "General / all genres", vibes: "Cozy & cat-friendly", hours: "9am–9pm", hasCafe: "Yes" } },
  //     { name: "Margin Notes", address: "31 Exmouth Market, EC1R 4QL", description: "Second-hand books, all priced at €5 or less.", detail: "Treasure hunting at its finest", personalNote: "Found a first edition here for €3. Still bragging.", meta: { specialty: "Second-hand", vibes: "Treasure trove", hours: "11am–5pm", hasCafe: "No" } },
  //     { name: "Open Book", address: "24hr — 2 Wigmore Street, W1U 2RD", description: "24-hour bookshop with a reading nook and blankets.", detail: "Yes, people do stay overnight", personalNote: "I have fallen asleep here. No regrets.", meta: { specialty: "General / all genres", vibes: "Sleepover energy", hours: "24 hours", hasCafe: "Yes" } },
  //     { name: "The Bookseller's Daughter", address: "9 Narrow Street, E14 8DJ", description: "Three generations of bookselling wisdom in one tiny shop.", detail: "Ask for a recommendation", personalNote: "The owner once talked me out of buying a book. Respect.", meta: { specialty: "Curated picks", vibes: "Intimate & wise", hours: "10am–5pm", hasCafe: "No" } },
  //   ],
  // },
  // {
  //   slug: "hikes",
  //   title: "Best Day Hikes Within 2 Hours",
  //   subtitle: "No overnight gear needed. Just good shoes and a sandwich.",
  //   emoji: "🥾",
  //   color: "#C8DCC4",
  //   image: "https://images.unsplash.com/photo-1605661480059-884578ac8ec8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoaWtpbmclMjB0cmFpbCUyMG1vdW50YWluJTIwdmlld3xlbnwxfHx8fDE3NzI4MzA0NTZ8MA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
  //   story: "I started hiking during lockdown when my only exercise was walking to the fridge. Now I'm the annoying friend who sends unsolicited photos of mountain views in the group chat. These trails are all doable in a day with zero wilderness survival skills (tested personally).",
  //   closingNote: "Always pack more water than you think you need. And a fully charged phone. My sense of direction is... aspirational.",
  //   tableColumns: [
  //     { key: "duration", label: "Duration", emoji: "⏱️" },
  //     { key: "difficulty", label: "Difficulty", emoji: "💪" },
  //     { key: "bestSeason", label: "Best season", emoji: "📅" },
  //     { key: "dogFriendly", label: "Dog friendly?", emoji: "🐕" },
  //     { key: "pubNearby", label: "Pub nearby?", emoji: "🍺" },
  //   ],
  //   items: [
  //     { name: "Eagle Ridge Loop", address: "Trailhead: Eagle Ridge Car Park, Lake District, CA12 5UQ", description: "Panoramic views from the summit, wildflowers in spring.", detail: "3 hours, moderate difficulty", personalNote: "I cried at the view. Not ashamed.", meta: { duration: "3 hrs", difficulty: "Moderate", bestSeason: "Spring–Autumn", dogFriendly: "Yes", pubNearby: "No" } },
  //     { name: "Coastal Path North", address: "Start: Whitby Abbey car park, YO22 4JT", description: "Clifftop walking with dramatic sea stacks and seabird colonies.", detail: "5 hours point-to-point", personalNote: "Pack extra snacks. You'll want to linger at every viewpoint.", meta: { duration: "5 hrs", difficulty: "Moderate–Hard", bestSeason: "Summer", dogFriendly: "On lead", pubNearby: "At finish" } },
  //     { name: "The Old Mill Trail", address: "Mill Lane Trailhead, Cotswolds, GL54 2HQ", description: "Follows an abandoned railway through forest and past ruins.", detail: "2 hours, easy and flat", personalNote: "Perfect for a hangover hike. Don't ask how I know.", meta: { duration: "2 hrs", difficulty: "Easy", bestSeason: "Year-round", dogFriendly: "Yes", pubNearby: "Trailhead" } },
  //     { name: "Summit of Mount Grey", address: "Grey Mountain Car Park, Snowdonia, LL55 4UL", description: "The classic local peak. Tough but rewarding.", detail: "4 hours, bring layers for the top", personalNote: "My legs didn't speak to me for 2 days after.", meta: { duration: "4 hrs", difficulty: "Hard", bestSeason: "Summer–Autumn", dogFriendly: "Fit dogs only", pubNearby: "No" } },
  //     { name: "Bluebell Woods Circuit", address: "Bluebell Woods NT, Ashridge Estate, HP4 1LT", description: "Best in April when the entire forest floor turns purple.", detail: "1.5 hours, family-friendly", personalNote: "Bring a camera. Your phone won't do it justice.", meta: { duration: "1.5 hrs", difficulty: "Easy", bestSeason: "April (bluebells!)", dogFriendly: "Yes", pubNearby: "5 min drive" } },
  //     { name: "Gorge Walk", address: "Gorge Trail Access, Brecon Beacons, SA11 5NR", description: "Narrow canyon with waterfalls and ancient moss-covered rocks.", detail: "2.5 hours, can be slippery", personalNote: "Feels like walking into a fantasy novel.", meta: { duration: "2.5 hrs", difficulty: "Moderate", bestSeason: "Autumn", dogFriendly: "Not ideal", pubNearby: "No" } },
  //     { name: "The Pilgrim's Way", address: "Start: Winchester Cathedral, SO23 9LS", description: "Historic route connecting two ancient villages.", detail: "6 hours, bring a picnic", personalNote: "The pub at the end village has earned its place in my heart.", meta: { duration: "6 hrs", difficulty: "Moderate", bestSeason: "Spring–Summer", dogFriendly: "Yes", pubNearby: "At finish" } },
  //   ],
  // },
  // {
  //   slug: "vinyl",
  //   title: "Best Record Shops for Vinyl",
  //   subtitle: "Digging through crates is my cardio.",
  //   emoji: "🎵",
  //   color: "#D4D4D4",
  //   image: "https://images.unsplash.com/photo-1645986052988-58547797dc4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2aW55bCUyMHJlY29yZCUyMHNob3AlMjBjcmF0ZXN8ZW58MXx8fHwxNzcyODMwNDU2fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
  //   story: "I bought my first record player in 2019 and swore I'd only buy \"a few records.\" Reader, I now own 400+. My Spotify Wrapped is embarrassing compared to my vinyl collection. These are the shops that enabled my beautiful, expensive addiction.",
  //   closingNote: "Set a budget before you walk in. Then accept that you will exceed it. It's the circle of life.",
  //   tableColumns: [
  //     { key: "genres", label: "Top genres", emoji: "🎶" },
  //     { key: "priceRange", label: "Avg. price", emoji: "💰" },
  //     { key: "newUsed", label: "New / Used", emoji: "📀" },
  //     { key: "listening", label: "Listening?", emoji: "🎧" },
  //   ],
  //   items: [
  //     { name: "Wax & Wane", address: "16 Berwick Street, W1F 0HP", description: "Deep jazz and soul collection curated by a former DJ.", detail: "Listening station in the back", personalNote: "The owner once played me a record that changed my entire taste.", meta: { genres: "Jazz, Soul, Funk", priceRange: "€15–€40", newUsed: "Mostly used", listening: "Yes" } },
  //     { name: "Rotate", address: "33 Oldham Street, M1 1JG", description: "New releases, local artists, and in-store performances.", detail: "Check their Instagram for events", personalNote: "Saw a band here before they blew up. Very smug about it.", meta: { genres: "Indie, Alt, Local", priceRange: "€20–€35", newUsed: "Mostly new", listening: "In-store" } },
  //     { name: "The Groove Merchant", address: "687 Haight Street, San Francisco 94117", description: "Funk, disco, and rare groove at fair prices.", detail: "The owner knows everything", personalNote: "Name any song and he'll find it. I've tested this.", meta: { genres: "Funk, Disco, Rare groove", priceRange: "€10–€50", newUsed: "Used", listening: "Ask owner" } },
  //     { name: "Dusty Fingers", address: "52 Rue des Vinaigriers, 75010", description: "Hip-hop and electronic with a serious rare section.", detail: "Cash gets you a better deal", personalNote: "Where I found a sealed Madvillain pressing. My white whale.", meta: { genres: "Hip-hop, Electronic", priceRange: "€8–€100+", newUsed: "Both", listening: "Yes" } },
  //     { name: "Analog Dreams", address: "27 Kottbusser Damm, 10967 Berlin", description: "Ambient, experimental, and everything in between.", detail: "Bring headphones", personalNote: "I go here when the world is too loud.", meta: { genres: "Ambient, Experimental", priceRange: "€15–€30", newUsed: "New", listening: "Headphone station" } },
  //     { name: "Spin Cycle", address: "11 Inverness Street, NW1 7HB", description: "High-turnover used section where gems appear daily.", detail: "Visit often, stock changes fast", personalNote: "Found a Beatles white album for €8. Still buzzing.", meta: { genres: "Everything", priceRange: "€3–€20", newUsed: "Used", listening: "No" } },
  //     { name: "Pressed", address: "75 Stoke Newington Road, N16 8AD", description: "Café-meets-record-shop with great coffee and better music.", detail: "They roast their own beans too", personalNote: "Two of my hobbies in one room. Dangerous.", meta: { genres: "Indie, Singer-songwriter", priceRange: "€18–€30", newUsed: "New", listening: "Café plays vinyl" } },
  //     { name: "The B-Side", address: "48 Hanway Street, W1T 1UU", description: "Punk, post-punk, and indie. Floor to ceiling.", detail: "Zines and patches by the register", personalNote: "The staff recommendations board is always right.", meta: { genres: "Punk, Post-punk, Indie", priceRange: "€10–€25", newUsed: "Both", listening: "No" } },
  //     { name: "Echoes", address: "3 Flask Walk, NW3 1HJ", description: "Classical and world music specialists with deep knowledge.", detail: "They'll order anything for you", personalNote: "Where I go to feel cultured and buy Debussy on vinyl.", meta: { genres: "Classical, World", priceRange: "€12–€35", newUsed: "New", listening: "Yes" } },
  //   ],
  // },
  // {
  //   slug: "sunset",
  //   title: "Best Spots to Watch the Sunset",
  //   subtitle: "Because sometimes you just need to sit and stare at the sky.",
  //   emoji: "🌅",
  //   color: "#F0D5C0",
  //   image: "https://images.unsplash.com/photo-1662180309544-eb1e5870efe0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnb2xkZW4lMjBzdW5zZXQlMjBvY2VhbiUyMGhvcml6b258ZW58MXx8fHwxNzcyODMwNDU3fDA&ixlib=rb-4.1.0&q=80&w=1080&utm_source=figma&utm_medium=referral",
  //   story: "I used to think watching sunsets was cheesy. Then I sat on Observatory Hill one evening with nothing to do and nowhere to be, and the sky turned every color I've ever loved. Now I'm the person who texts friends \"LOOK OUTSIDE RIGHT NOW\" at 8pm. No regrets.",
  //   closingNote: "The best sunset is the one you actually stop to watch. Put your phone down for the first five minutes. Then take 200 photos. Balance.",
  //   tableColumns: [
  //     { key: "setting", label: "Setting", emoji: "🏔️" },
  //     { key: "bestSeason", label: "Best season", emoji: "📅" },
  //     { key: "crowd", label: "Crowd", emoji: "👥" },
  //     { key: "bringWhat", label: "Bring", emoji: "🎒" },
  //     { key: "romantic", label: "Romance factor", emoji: "💕" },
  //   ],
  //   items: [
  //     { name: "Observatory Hill", address: "Observatory Hill Park, Watson Road, Millers Point NSW 2000", description: "The classic. Unobstructed 270-degree views of the skyline.", detail: "Arrive 30 minutes early", personalNote: "This is where it all started for me. My origin story.", meta: { setting: "Hilltop park", bestSeason: "Year-round", crowd: "Busy", bringWhat: "Blanket", romantic: "★★★★★" } },
  //     { name: "West Pier Ruins", address: "Kings Road, Brighton BN1 2FL", description: "Silhouetted iron frame against orange and purple skies.", detail: "Bring a camera", personalNote: "Every photo looks like a postcard. It's almost unfair.", meta: { setting: "Beachfront", bestSeason: "Autumn", crowd: "Medium", bringWhat: "Camera", romantic: "★★★★☆" } },
  //     { name: "The Rooftop at Hotel Mira", address: "Hotel Mira, 18 Henrietta Street, WC2E 8QH", description: "Cocktails with a sunset backdrop. Worth the splurge.", detail: "Book a table by the railing", personalNote: "Where I take people I'm trying to impress. Works every time.", meta: { setting: "Rooftop bar", bestSeason: "Summer", crowd: "Exclusive", bringWhat: "Credit card", romantic: "★★★★★" } },
  //     { name: "Shepherd's Meadow", address: "Off Shepherd's Way, South Downs, BN7 1RS", description: "Open field on the edge of town, wildflowers in summer.", detail: "Pack a blanket and wine", personalNote: "I proposed... a toast here once. Just a toast. Relax.", meta: { setting: "Open meadow", bestSeason: "Summer", crowd: "Low", bringWhat: "Wine & blanket", romantic: "★★★★★" } },
  //     { name: "South Beach Dunes", address: "South Beach Access Road, Camber Sands, TN31 7RT", description: "Sit in the dune grass and watch the sun melt into the sea.", detail: "Best in late summer", personalNote: "The sand is still warm at sunset. Nature's heated blanket.", meta: { setting: "Sand dunes", bestSeason: "Late summer", crowd: "Medium", bringWhat: "Towel", romantic: "★★★★☆" } },
  //     { name: "The Canal Bridge", address: "Bridge 49, Regent's Canal, N1 8QH", description: "Water reflects the sky perfectly. Double sunset.", detail: "Locals gather here naturally", personalNote: "Strangers become friends here. It's that kind of spot.", meta: { setting: "Canal bridge", bestSeason: "Year-round", crowd: "Locals", bringWhat: "Good company", romantic: "★★★☆☆" } },
  //     { name: "Cemetery Hill", address: "Highgate Cemetery, Swain's Lane, N6 6PJ", description: "Peaceful, quiet, and unexpectedly beautiful at golden hour.", detail: "Respectful silence appreciated", personalNote: "Sounds weird, feels profound.", meta: { setting: "Hilltop cemetery", bestSeason: "Autumn", crowd: "Very low", bringWhat: "Silence", romantic: "★★★☆☆" } },
  //     { name: "The Breakwater", address: "Breakwater Walk, Portland Harbour, DT5 1PP", description: "Walk to the very end and feel like you're in the ocean.", detail: "Can be windy — dress warm", personalNote: "The wind makes you feel dramatic. Lean into it.", meta: { setting: "Ocean pier", bestSeason: "Spring–Autumn", crowd: "Low", bringWhat: "Warm jacket", romantic: "★★★★☆" } },
  //   ],
  // },
];
